# Generated by Django 5.1.2 on 2024-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineexercise',
            name='duration',
            field=models.TextField(help_text='Duración específica minutos o repeticiones'),
        ),
    ]
