# Generated by Django 5.1.2 on 2024-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_alter_routineexercise_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Strength', 'Fuerza'), ('Cardio', 'Cardio')], default='Strength', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Principiante'), ('Intermediate', 'Intermedio'), ('Advanced', 'Avanzado')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
