# Generated by Django 5.1.2 on 2024-11-29 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_exercise_equipment_exercise_exercise_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Strength', 'Fuerza'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibilidad')], default='Strength', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
