# Generated by Django 5.1.2 on 2024-12-17 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='enrollments',
            field=models.ManyToManyField(blank=True, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='max_enrolls',
            field=models.IntegerField(default=10),
        ),
    ]
